### PR TITLE
WIP: Learning about color pickers

### PR DESCRIPTION
**Pull request by raldi**

### CODE REVIEW

**Comment by raldi** [comment]
The existing Checkers pattern uses two hardcoded RGB values. I'm trying out different ways to make them dynamic. I'd like to subclass https://github.com/heronarts/LX/blob/master/src/main/java/heronarts/lx/pattern/color/SolidPattern.java but we're already inheriting from TEPattern to get access to the model, so instead I took all SolidPattern's guts and stuck them into a class called TEColor.

**Comment by raldi** [comment]
It seems to almost work, but instead of getting a nice mini control panel like subclasses of SolidPattern get...

Screen Shot 2022-02-09 at 4 22 46 PM

...we get this abomination:

Screen Shot 2022-02-09 at 4 24 09 PM

**Comment by raldi** [comment]
Digging into the LX code to figure out what magic SolidPattern uses to get its UI elements to render as cool sliders and pickers and textboxes that appear and disappear on cue, instead of all these always-visible knobs...

**Comment by raldi** [comment]
It appears I've got this working now:

checkers

**Comment by raldi** [comment]
Added column labels 
Screen Shot 2022-02-10 at 11 46 18 AM

**Comment by mcslee** [comment]
> It appears I've got this working now:
> 
> checkers

Looks very nice!

**Review by mcslee — APPROVED** [review]

**Comment by raldi** [comment]
I probably should've renamed this before merging but YOLO

**Pull request merged**
